[project]
name = 'Quantum-Computing-Resource-Allocation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.job-scheduler]
path = 'contracts/job-scheduler.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-tracker]
path = 'contracts/performance-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-marketplace]
path = 'contracts/quantum-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-time-token]
path = 'contracts/quantum-time-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
